import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import Homepage from '../components/Homepage';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />

      </Head>
        <Homepage />
    </>
  );
};

export default Home;
